include ../../../../Config

BINTARGET = ../../../../bin/initrd/sys/lib/$(TARGET)
SRCS = $(wildcard *.c)
SRCS += $(wildcard *.S)
TMP = $(SRCS:.c=.o)
OBJS = $(TMP:.S=.o)
LIBS += -lc
export O

CFLAGS += -Wall -fPIC -ffreestanding -fvisibility=hidden -DOSZ_LIBRARY=1 -nostdinc -I../../../../etc/include -I../../../core/$(ARCH)
LDFLAGS += -nostdlib -nodefaultlibs -nostartfiles -shared -L../../../../bin/initrd/sys/lib

all: $(OBJS) $(BINTARGET)

%.o: %.S
	$(O)$(CC) -I../../../../etc/include $(OPT) $(CFLAGS) -c $< -o $@

%.o: %.c
	$(O)$(CC) -I../../../../etc/include $(OPT) $(CFLAGS) -c $< -o $@

$(BINTARGET):
	@echo "  src		$(TARGET)"
	@mkdir -p ../../../../bin/initrd/sys/lib/$(dir $(TARGET))
	$(O)$(CC) $(LDFLAGS) $(OBJS) -Xlinker --build-id=none -T ../../../core/$(ARCH)/sharedlib.ld -o $(BINTARGET) $(LIBS)

clean:
	@rm *.o $(BINTARGET) 2>/dev/null || true
