/*
 * libc/str.S
 * 
 * Copyright 2016 CC-by-nc-sa-4.0 bztsrc@github
 * https://creativecommons.org/licenses/by-nc-sa/4.0/
 * 
 * You are free to:
 *
 * - Share — copy and redistribute the material in any medium or format
 * - Adapt — remix, transform, and build upon the material
 *     The licensor cannot revoke these freedoms as long as you follow
 *     the license terms.
 * 
 * Under the following terms:
 *
 * - Attribution — You must give appropriate credit, provide a link to
 *     the license, and indicate if changes were made. You may do so in
 *     any reasonable manner, but not in any way that suggests the
 *     licensor endorses you or your use.
 * - NonCommercial — You may not use the material for commercial purposes.
 * - ShareAlike — If you remix, transform, or build upon the material,
 *     you must distribute your contributions under the same license as
 *     the original.
 *
 * @brief Low level string operations
 */

.global strcpy
.global strncpy
.global strcat
.global strncat
.global strcmp
.global strncmp
.global strdup
.global strndup
.global strchr
.global strrchr
.global strstr
.global strlen
.global strnlen
.global strerror
.global ffs
.global strcasecmp
.global strncasecmp
.global strsignal
.global basename
.global dirname
.global sprintf

.section .text
strcpy:
	ret

strncpy:
	ret

strcat:
	ret

strncat:
	ret

strcmp:
	ret

strncmp:
	ret

strdup:
	ret

strndup:
	ret

strchr:
	ret

strrchr:
	ret

strstr:
	ret

strlen:
	ret

strnlen:
	ret

strerror:
	ret

ffs:
	ret

strcasecmp:
	ret

strncasecmp:
	ret

strsignal:
	ret

basename:
	ret

dirname:
	ret

sprintf:
	ret
