include ../../../../Config

BINTARGET = ../../../../bin/initrd/lib/sys/$(TARGET)
SRCS = $(wildcard *.c)
SRCS += $(wildcard *.S)
TMP = $(SRCS:.c=.o)
OBJS = $(TMP:.S=.o)
LIBS += -lc

CFLAGS += -DDEBUG=$(DEBUG) -DOPTIMIZE=$(OPTIMIZE) -Wall -fPIC -ffreestanding -fvisibility=hidden -DOSZ_DRIVER=1 -nostdinc -I../../../../etc/include -I../../../core/$(ARCH)
LDFLAGS += -nostdlib -nodefaultlibs -nostartfiles -shared -L../../../../bin/initrd/lib -lc

all: $(OBJS) $(BINTARGET)

%.o: %.S
	$(O)$(CC) $(OPT) $(CFLAGS) -c $< -o $@

%.o: %.c
	$(O)$(CC) $(OPT) $(CFLAGS) -c $< -o $@

$(BINTARGET):
	@echo "  src		$(TARGET)"
	@mkdir -p ../../../../bin/initrd/lib/sys/$(firstword $(subst /, ,$(TARGET)))
	@../../../../tools/drivers.sh $(TARGET)
	$(O)$(CC) $(LDFLAGS) $(OBJS) -Xlinker --build-id=none -T ../../../core/$(ARCH)/sharedlib.ld -o $(BINTARGET) $(LIBS)

clean:
	@rm *.o $(BINTARGET) 2>/dev/null || true
