include ../../../../Config

BINTARGET = ../../../../bin/initrd/sys/drv/$(TARGET)
SRCS = $(wildcard *.c)
SRCS += $(wildcard *.S)
TMP = $(SRCS:.c=.o)
OBJS = $(TMP:.S=.o)
LIBS += -lc

CFLAGS += -DDEBUG=$(DEBUG) -DOPTIMIZE=$(OPTIMIZE) -Wall -fPIC -ffreestanding -fvisibility=hidden -fno-stack-protector -nostdinc \
-I../../../../etc/include -I../../../core/$(ARCH) -I../../../lib/libc -I../../../lib/libc/$(ARCH) -I../../../fs
LDFLAGS += -nostdlib -shared -Bshareable -L../../../../bin/initrd/sys/lib -L../../../lib -lc

all: $(OBJS) $(EXTOBJS) $(BINTARGET)

%.o: %.S
	$(O)$(CC) $(OPT) $(CFLAGS) -c $< -o $@

%.o: %.c
	$(O)$(CC) $(OPT) $(CFLAGS) -c $< -o $@

$(BINTARGET):
	@echo "  src		sys/drv/$(TARGET)"
	@mkdir -p ../../../../bin/initrd/sys/drv/$(firstword $(subst /, ,$(TARGET)))
	@../../../../tools/drivers.sh $(TARGET)
	$(O)$(LD) $(LDFLAGS) $(EXTOBJS) $(OBJS) --build-id=none -T ../../../sharedlib.ld -o $(BINTARGET) $(LIBS)

clean:
	@rm *.o $(BINTARGET) 2>/dev/null || true
