/*
 * sys/inet.h - GENERATED BY elftool DO NOT EDIT THIS FILE
 *
 * Copyright 2017 CC-by-nc-sa bztsrc@github
 * https://creativecommons.org/licenses/by-nc-sa/4.0/
 * 
 * You are free to:
 *
 * - Share — copy and redistribute the material in any medium or format
 * - Adapt — remix, transform, and build upon the material
 *     The licensor cannot revoke these freedoms as long as you follow
 *     the license terms.
 *
 * Under the following terms:
 *
 * - Attribution — You must give appropriate credit, provide a link to
 *     the license, and indicate if changes were made. You may do so in
 *     any reasonable manner, but not in any way that suggests the
 *     licensor endorses you or your use.
 * - NonCommercial — You may not use the material for commercial purposes.
 * - ShareAlike — If you remix, transform, or build upon the material,
 *     you must distribute your contributions under the same license as
 *     the original.
 *
 * @brief OS/Z system calls for inet service. Include with osZ.h
 */

#define SYS_recvfrom	(0x05)
#define SYS_connect	(0x06)
#define SYS_getsockopt	(0x07)
#define SYS_bind	(0x0a)
#define SYS_socket	(0x0b)
#define SYS_getpeername	(0x0c)
#define SYS_setsockopt	(0x0e)
#define SYS_sendto	(0x0f)
#define SYS_getsockname	(0x10)
#define SYS_sendmsg	(0x11)
#define SYS_listen	(0x12)
#define SYS_accept	(0x13)
#define SYS_shutdown	(0x14)
#define SYS_socketpair	(0x15)
#define SYS_recvmsg	(0x16)

