/*
 * sys/net.h - GENERATED BY elftool DO NOT EDIT THIS FILE
 *
 * Copyright 2017 CC-by-nc-sa bztsrc@github
 * https://creativecommons.org/licenses/by-nc-sa/4.0/
 * 
 * You are free to:
 *
 * - Share — copy and redistribute the material in any medium or format
 * - Adapt — remix, transform, and build upon the material
 *     The licensor cannot revoke these freedoms as long as you follow
 *     the license terms.
 *
 * Under the following terms:
 *
 * - Attribution — You must give appropriate credit, provide a link to
 *     the license, and indicate if changes were made. You may do so in
 *     any reasonable manner, but not in any way that suggests the
 *     licensor endorses you or your use.
 * - NonCommercial — You may not use the material for commercial purposes.
 * - ShareAlike — If you remix, transform, or build upon the material,
 *     you must distribute your contributions under the same license as
 *     the original.
 *
 * @brief OS/Z system calls for net service. Include with osZ.h
 */

#define SYS_recvfrom	(  2)
#define SYS_connect	(  3)
#define SYS_getsockopt	(  4)
#define SYS_bind	(  7)
#define SYS_socket	(  8)
#define SYS_getpeername	(  9)
#define SYS_setsockopt	( 12)
#define SYS_sendto	( 13)
#define SYS_getsockname	( 14)
#define SYS_sendmsg	( 15)
#define SYS_listen	( 16)
#define SYS_accept	( 17)
#define SYS_shutdown	( 18)
#define SYS_socketpair	( 19)
#define SYS_recvmsg	( 20)

