/*
 * sys/ui.h - GENERATED BY elftool DO NOT EDIT THIS FILE
 *
 * Copyright 2017 CC-by-nc-sa bztsrc@github
 * https://creativecommons.org/licenses/by-nc-sa/4.0/
 * 
 * You are free to:
 *
 * - Share — copy and redistribute the material in any medium or format
 * - Adapt — remix, transform, and build upon the material
 *     The licensor cannot revoke these freedoms as long as you follow
 *     the license terms.
 *
 * Under the following terms:
 *
 * - Attribution — You must give appropriate credit, provide a link to
 *     the license, and indicate if changes were made. You may do so in
 *     any reasonable manner, but not in any way that suggests the
 *     licensor endorses you or your use.
 * - NonCommercial — You may not use the material for commercial purposes.
 * - ShareAlike — If you remix, transform, or build upon the material,
 *     you must distribute your contributions under the same license as
 *     the original.
 *
 * @brief OS/Z system calls for ui service. Include with osZ.h
 */

#define SYS_opentty	( 14)
#define SYS_openwrd	( 16)
#define SYS_openwin	( 21)
#define SYS_setcursor	( 24)
#define SYS_keypress	( 27)
#define SYS_keyrelease	( 30)
#define SYS_pointer	( 34)

