BINTARGET = ../../bin/root/$(TARGET)
SRCS = $(wildcard *.c)
OBJS = $(SRCS:.c=.o)
LIBS += -lc

CFLAGS += -Wall -fpic -ffreestanding
LDFLAGS += -nostdlib -nodefaultlibs -nostartfiles

all: $(OBJS) $(BINTARGET)

%.o: %.c
	@$(CC) -I../../etc/include $(OPT) $(CFLAGS) -c $< -o $@

$(BINTARGET):
	@echo "  src		$(TARGET)"
	@$(CC) $(LDFLAGS) $(OBJS) -Xlinker --build-id=none -T ../executable.ld -o $(BINTARGET) $(LIBS)

clean:
	@rm *.o $(BINTARGET) 2>/dev/null || true
