include ../../Config
BINTARGET = ../../bin/root/$(TARGET)
SRCS = $(wildcard *.c)
OBJS = $(SRCS:.c=.o)
LIBS += -lc

CFLAGS += -Wall -fpic -fPIC -ffreestanding
LDFLAGS += -nostdlib -nodefaultlibs -nostartfiles -L../../bin/root/lib
ifeq ($(LINKER),sharedlib)
LDFLAGS += -shared -Bsymbolic -Bshareable
endif

ifeq ($(LINKER),)
LINKER = executable
endif

all: $(OBJS) $(BINTARGET)

%.o: %.c
	@$(CC) -I../../etc/include $(OPT) $(CFLAGS) -c $< -o $@

$(BINTARGET):
	@echo "  src		$(TARGET)"
	@$(CC) $(LDFLAGS) $(OBJS) $(EXTOBJ) -Xlinker --build-id=none -T ../core/$(ARCH)/$(LINKER).ld -o $(BINTARGET) $(LIBS)

clean:
	@rm *.o $(BINTARGET) 2>/dev/null || true
