BINTARGET = ../../../../bin/root/lib/sys/$(TARGET)
SRCS = $(wildcard *.c)
OBJS = $(SRCS:.c=.o)
LIBS += -lc

CFLAGS += -Wall -fpic -fPIC -ffreestanding
LDFLAGS += -nostdlib -nodefaultlibs -nostartfiles -shared -fPIC

all: $(OBJS) $(BINTARGET)

%.o: %.c
	@$(CC) -I../../../../etc/include $(OPT) $(CFLAGS) -c $< -o $@

$(BINTARGET):
	@echo "  src		$(TARGET)"
	@mkdir -p ../../../../bin/root/lib/sys/$(firstword $(subst /, ,$(TARGET)))
	@$(CC) $(LDFLAGS) $(OBJS) -Xlinker --build-id=none -T ../../../sharedlib.ld -o $(BINTARGET) $(LIBS)

clean:
	@rm *.o $(BINTARGET) 2>/dev/null || true
